server:
  port: 8041
  
spring:
   data:
    mongodb:
      uri: mongodb://localhost:27017/microservicio02
      
eureka:
   client:        
     serviceUrl:
      defaultZone: http://localhost:8761/eureka 
      
      #https://TU_RUTA-eureka.herokuapp.com/eureka/ 
